title: Fabrício Giordanelli # your name (or website title) here
logo: "/images/Fabrício.png?raw=true" # your photo (or logo) here
description: aaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
theme: jekyll-theme-minimal
google_analytics:
