title: Fabrício Giordanelli # your name (or website title) here
logo: "/images/Fabrício.png?raw=true" # your photo (or logo) here
description: 
<br>
Fabrício Giordanelli já trabalhou em quatro grandes seguradoras na área estatística com modelos de precificação e elasticidade, machine learning aplicada à fraude e subscrição. Desenvolveu painéis e relatórios em R (utlizando markdown e shiny), Python, VBA e SAS/SQL para prever e dectetar riscos e padrões comportamentais.
<br>
theme: jekyll-theme-minimal
google_analytics:
